name: shopzo
description: "Shopzo - Simple. Smart. Sell. Supermarket Management Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  pdf: ^3.10.8
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/shopzo_app_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/shopzo_app_icon.png"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/images/
